from document.constants import (
    DefaultConfidence,
    FGLabels,
    TBLabels,
)

env = dict(
    accessKey="${fileUsername}",
    accessSecret="${filePassword}",
    annotationBase="layout/processed/",
    cacheDir="/app/hf_models_cache",
    callbackAPIKey="${validUsername}",
    deviceType="${deviceType}",
    includeLS=False,
    layoutBroker="redis://${cacheAddr}:${cachePort}/0",
    layoutLogger="${layoutService}",
    layoutResultBroker="redis://${cacheAddr}:${cachePort}/0",
    ocrBase="layout/raw/",
    ocrCredentials="credentials.json",
    ocrProject="${ocrProject}",
    ocrType="${ocrType}",
    productionModels={
        "figure": {
            "confidence": DefaultConfidence,
            "name": "${figureModel}",
            "labels": FGLabels,
            "pth": "${figureModelPth}",
            "yml": "${figureModelYml}",
        },
        "table": {
            "confidence": DefaultConfidence,
            "name": "${tableModel}",
            "labels": TBLabels,
            "pth": "${tableModelPth}",
            "yml": "${tableModelYml}",
        },
    },
    queueType="kafka",
    uploadBase="layout/processed/",
    uploadBaseURL="${fileBaseDomain}",
    uploadBucket="${uploadBucket}",
    uploadReplaceURL="${fileSSL ? "https" : "http"}://${fileBaseDomain}/${uploadBucket}/",
    uploadSSL=${fileSSL ? "True" : "False"},
    uploadType="minio",
    uploadURL="${fileSSL ? "https" : "http"}://${fileBaseDomain}/${uploadBucket}/",
    validAPIKeys=["${validAPIKey}", "${validUsername}"],
)
