from document.constants import (
    DefaultConfidence,
    FGLabels,
    HJLabels,
    TBLabels,
)

env = dict(
    annotationBase="",
    annotationQueueDev="",
    annotationQueueProd="",
    annotationRegionDev="",
    annotationRegionProd="",
    awsKey="",
    awsSecret="",
    cacheDir="/app/hf_models_cache",
    callbackAPIKey="${validAPIKey}",
    deviceType="${deviceType}",
    layoutRegionProd="",
    layoutBroker="redis://${cacheService}.${namespace}.svc.cluster.local:6379/0",
    layoutCache="${cacheService}.${namespace}.svc.cluster.local",
    layoutResultBroker="redis://${cacheService}.${namespace}.svc.cluster.local:6379/0",
    layoutLog="${layoutService}",
    layoutModelName="${layoutModelName}",
    ocrBase="layout/raw/",
    ocrBucket="eyelevel-upload",
    ocrCredentials="",
    ocrProject="",
    productionModels={
        "figure": {
            "confidence": DefaultConfidence,
            "name": "fg_faster_rcnn_R_50_FPN_3x - fine tuned",
            "labels": FGLabels,
            "pth": "https://upload.groundx.ai/layout/model/current/fg_faster_rcnn_R_50_FPN_3x.071924.pth",
            "yml": "https://upload.groundx.ai/layout/model/current/fg_faster_rcnn_R_50_FPN_3x_config.071924.yml",
        },
        "table": {
            "confidence": DefaultConfidence,
            "name": "tb_faster_rcnn_R_101_FPN_3x - fine tuned 2-21-2024",
            "labels": TBLabels,
            "pth": "https://upload.groundx.ai/layout/model/current/tb_faster_rcnn_R_101_FPN_3x.pth",
            "yml": "https://upload.groundx.ai/layout/model/current/tb_faster_rcnn_R_101_FPN_3x_config.yml",
        },
    },
    uploadBase="layout/processed/",
    uploadBucket="eyelevel-upload",
    uploadReplaceURL="https://eyelevel-upload.s3.us-west-2.amazonaws.com/",
    uploadURL="https://upload.eyelevel.ai/",
    validAPIKeys=["${validAPIKey}"],
)
