from document.constants import (
    DefaultConfidence,
    FGLabels,
    TBLabels,
)

env = dict(
    accessKey="${fileAccessKey}",
    accessSecret="${fileAccessSecret}",
    annotationBase="layout/processed/",
    cacheDir="/app/hf_models_cache",
    callbackAPIKey="${validAPIKey}",
    deviceType="${deviceType}",
    includeLS=False,
    layoutBroker="redis://${cacheService}.${namespace}.svc.cluster.local:6379/0",
    layoutCache="${cacheService}.${namespace}.svc.cluster.local",
    layoutLogger="${layoutService}",
    layoutResultBroker="redis://${cacheService}.${namespace}.svc.cluster.local:6379/0",
    ocrBase="layout/raw/",
    ocrCredentials="",
    ocrProject="",
    productionModels={
        "figure": {
            "confidence": DefaultConfidence,
            "name": "${layoutModelName}",
            "labels": FGLabels,
            "pth": "https://upload.groundx.ai/layout/model/current/fg_faster_rcnn_R_50_FPN_3x.071924.pth",
            "yml": "https://upload.groundx.ai/layout/model/current/fg_faster_rcnn_R_50_FPN_3x_config.071924.yml",
        },
        "table": {
            "confidence": DefaultConfidence,
            "name": "${layoutModelName}",
            "labels": TBLabels,
            "pth": "https://upload.groundx.ai/layout/model/current/tb_faster_rcnn_R_101_FPN_3x.pth",
            "yml": "https://upload.groundx.ai/layout/model/current/tb_faster_rcnn_R_101_FPN_3x_config.yml",
        },
    },
    queueType="kafka",
    uploadBase="layout/processed/",
    uploadBaseURL="${fileService}.${namespace}.svc.cluster.local",
    uploadBucket="${uploadBucket}",
    uploadReplaceURL="http://${fileService}.${namespace}.svc.cluster.local/${uploadBucket}/",
    uploadSSL=${fileSSL},
    uploadType="minio",
    uploadURL="http://${fileService}.${namespace}.svc.cluster.local/${uploadBucket}/",
    validAPIKeys=["${validAPIKey}"],
)
