apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      nodeSelector:
        node_pool: "{{ .Values.nodeSelector.node }}"
      tolerations:
        - key: "node"
          value: "{{ .Values.nodeSelector.node }}"
          effect: "NoSchedule"
      initContainers:
      - name: wait-for-groundx
        image: {{ .Values.busybox.repository }}:{{ .Values.busybox.tag }}
        imagePullPolicy: "{{ .Values.busybox.pull }}"
        command: ['sh', '-c', "until wget --spider -q http://{{ .Values.dependencies.groundx }}:8080/health; do echo waiting for groundx; sleep 2; done"]
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pull }}"
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          fsGroup: {{ .Values.securityContext.fsGroup }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        {{- if not .Values.local }}
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /home/golang/.cashbot/config.yaml
          subPath: config.yaml
        - name: init-db-volume
          mountPath: /app/init-db.sql
          subPath: init-db.sql
      volumes:
      - name: config-volume
        configMap:
          name: config-yaml-map
      - name: init-db-volume
        configMap:
          name: init-database-file